<?php
$order_id = $block->getCurrentOrder();
$orderIdToDisplay = "";
$orderDetailsToDisplay = "";
$customerName = "";
$customerEmail = "";
$billingName = "";
$shippingName = "";
$purchaseDate = "";
$purchasePoint = "";

if ($order_id != 0) {
    $order = $block->getOrderById($order_id); // Fetch the entire order object
    if ($order) {
        $orderItemsCollection = $block->orderItemsCollection($order_id);
        $orderIdToDisplay = $order->getIncrementId();
        $customerName = $order->getCustomerName();
        $customerEmail = $order->getCustomerEmail();
        $billingName = $order->getBillingAddress()->getName();
        $shippingName = $order->getShippingAddress()->getName();
        $purchaseDate = $order->getCreatedAt();
        $purchasePoint = $order->getPurchasePoint();
    }
}
?>

<div class="order-card">
    <div class="order-id-div">
        <h1 class="inn_order_id_div">Order Research</h1>
        <div class="div_image">
            <img class="image_logo" src="<?php echo $block->getViewFileUrl('AsquareTec_OrderScanner::images/back_1.png'); ?>" alt="Your Image" />
    </div>
    </div>
   
    <div class="flex_div_order">
        <!-- <div class="order_head">
            <h1 class="inn_order_head">ORDER SCAN</h1>
        </div> -->
        <!-- <div class="search-bar">
            <input class="search-bar-inn" type="text" placeholder="Search Any SKU" />
        </div> -->
        <div class="flex_text">
            <div class="serch-result">Search Result</div>
                <div class="item-sku">Item Sku:</div>
            <button class="print-search">Print Search Results</button>

        </div>

    </div>
    <div class="order-det">
        <div class="order-details">
          <span class="high_light"></span> <span class="high_light_data" id="purchase-point-value"></span></p> 
        </div>

        <div class="order-table">
            <table class="f_table_order">
                <thead class="t_head_order">
                    <tr>
                        <th class="t_head">Order ID</th>
                        <th class="t_head">Order Date</th>
                        <th class="t_head">Customer Name</th>
                        <th class="t_head">Phone</th>
                        <th class="t_head">Email</th>
                        <th class="t_head extendpro">Product Name</th>
                        <th class="t_head extendsku">SKU</th>
                        <th class="t_head">Unit Price</th>
                        <th class="t_head">QT Ordered</th> <!-- New Quantity column -->
                    </tr>
                </thead>
                <tbody class="t_body_order">

                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="section-2">
    <div class="buyers-head">
        3 Most QT BUYERS
    </div>
    <div class="customer-summary">
    <div class="customer-card">
        <div class="badge badge-gold">
        <img src="<?php echo $block->getViewFileUrl('AsquareTec_OrderScanner::images/Group308.svg'); ?>" alt="Your Image" />
        </div>
        <div class="customer-details">
            <p><strong>Customer Name:</strong> Guy A</p>
            <p><strong>Total Orders:</strong> 3</p>
            <p><strong>Total QT:</strong> 3520</p>
            <p><strong>Phone:</strong> 305908809</p>
        </div>
    </div>
    
    <div class="customer-card">
        <div class="badge badge-silver">
        <img src="<?php echo $block->getViewFileUrl('AsquareTec_OrderScanner::images/Group307.svg'); ?>" alt="Your Image" />
        </div>
        <div class="customer-details">
            <p><strong>Customer Name:</strong> Guy A</p>
            <p><strong>Total Orders:</strong> 6</p>
            <p><strong>Total QT:</strong> 1500</p>
            <p><strong>Phone:</strong> 305908809</p>
        </div>
    </div>
    
    <div class="customer-card">
        <div class="badge badge-bronze">
        <img src="<?php echo $block->getViewFileUrl('AsquareTec_OrderScanner::images/Group306.svg'); ?>" alt="Your Image" />
        </div>
        <div class="customer-details">
            <p><strong>Customer Name:</strong> Guy A</p>
            <p><strong>Total Orders:</strong> 2</p>
            <p><strong>Total QT:</strong> 800</p>
            <p><strong>Phone:</strong> 305908809</p>
        </div>
    </div>
</div>


</div>

<script type="text/javascript">
    require(['jquery'], function($) {
        $(document).ready(function() {
            var customUrl = '<?= $block->getUrl('orderscanner/custom/OrderSearch') ?>';
            $(document).on("click", ".order-search-btn", function() {

         // Get the value of data-sku from the parent <tr>
                    var skuValue = $(this).closest('tr').data('sku');
                    performOrderSearch(skuValue);
                    // Do something with the skuValue
                    console.log(skuValue);
                });


           

            function performOrderSearch(sku) {
                var searchTerm = sku;

                if (!searchTerm) {
                    $('.order-det').html('Please enter an Order ID or Product Name.');
                    return;
                }

                $.ajax({
                    url: customUrl,
                    type: 'GET',
                    data: {
                        search: searchTerm,
                        isAjax: true
                    },
                    success: function(response) {
                        if (response.error) {
                            $('.order-det').html(response.error);
                        } else {
                            updateOrderDetails(response);
                        }
                    },
                    error: function() {
                        $('.order-det').html('An error occurred while searching.');
                    }
                });
            }

            function updateOrderDetails(orderData) {
                var orderDetailsHtml = '';

                // Clear previous results
                $('.t_body_order').empty();

                // Populate order details
                // orderDetailsHtml += '<tr>';
                //     orderDetailsHtml += '<td>' + order.order_id + '</td>';
                //     orderDetailsHtml += '<td>' + order.order_name + '</td>';
                //     orderDetailsHtml += '<td>' + order.customer_email + '</td>';
                //     orderDetailsHtml += '<td>' + order.billing_name + '</td>';
                //     orderDetailsHtml += '<td>' + order.shipping_name + '</td>';
                //     orderDetailsHtml += '<td>' + order.purchase_date + '</td>';
                //     orderDetailsHtml += '<td>' + order.sku.replace(/\n/g, '<br>') + '</td>'; // SKU with new lines
                //     orderDetailsHtml += '<td class="decreasefont">' + order.product_name.replace(/\n/g, '<br>') + '</td>'; // Product Name with new lines
                //     orderDetailsHtml += '<td>' + order.price.replace(/\n/g, '<br>') + '</td>'; // Price with new lines
                //     orderDetailsHtml += '<td>' + order.quantity.replace(/\n/g, '<br>') + '</td>'; // Quantity with new lines
                //     orderDetailsHtml += '</tr>';
                orderData.forEach(function(order) {
                    orderDetailsHtml += '<tr>';
                    orderDetailsHtml += '<td>' + order.order_id + '</td>';
                    orderDetailsHtml += '<td>' + order.purchase_date + '</td>';
                    orderDetailsHtml += '<td>' + order.order_name  + '</td>';
                    orderDetailsHtml += '<td>' + order.phone + '</td>'; // Add phone here
                    orderDetailsHtml += '<td>' + order.customer_email + '</td>';
                    orderDetailsHtml += '<td class="decreasefont">' + order.product_name.replace(/\n/g, '<br>')  + '</td>';
                    orderDetailsHtml += '<td>' + order.sku.replace(/\n/g, '<br>') + '</td>'; // SKU with new lines
                    orderDetailsHtml += '<td >' + order.price.replace(/\n/g, '<br>') + '</td>'; // Product Name with new lines
                    orderDetailsHtml += '<td>' + order.quantity.replace(/\n/g, '<br>') + '</td>'; // Price with new lines
                    //orderDetailsHtml += '<td>' + order.quantity.replace(/\n/g, '<br>') + '</td>'; // Quantity with new lines
                    orderDetailsHtml += '</tr>';
                });

                $('.t_body_order').html(orderDetailsHtml);
            }
        });
    });
</script>
